package com.zhang.example02mbg.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CustomerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public CustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRowidIsNull() {
            addCriterion("rowid is null");
            return (Criteria) this;
        }

        public Criteria andRowidIsNotNull() {
            addCriterion("rowid is not null");
            return (Criteria) this;
        }

        public Criteria andRowidEqualTo(Integer value) {
            addCriterion("rowid =", value, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidNotEqualTo(Integer value) {
            addCriterion("rowid <>", value, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidGreaterThan(Integer value) {
            addCriterion("rowid >", value, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidGreaterThanOrEqualTo(Integer value) {
            addCriterion("rowid >=", value, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidLessThan(Integer value) {
            addCriterion("rowid <", value, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidLessThanOrEqualTo(Integer value) {
            addCriterion("rowid <=", value, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidIn(List<Integer> values) {
            addCriterion("rowid in", values, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidNotIn(List<Integer> values) {
            addCriterion("rowid not in", values, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidBetween(Integer value1, Integer value2) {
            addCriterion("rowid between", value1, value2, "rowid");
            return (Criteria) this;
        }

        public Criteria andRowidNotBetween(Integer value1, Integer value2) {
            addCriterion("rowid not between", value1, value2, "rowid");
            return (Criteria) this;
        }

        public Criteria andCompany_idIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompany_idIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompany_idEqualTo(String value) {
            addCriterion("company_id =", value, "company_id");
            return (Criteria) this;
        }

        public Criteria andCompany_idNotEqualTo(String value) {
            addCriterion("company_id <>", value, "company_id");
            return (Criteria) this;
        }

        public Criteria andCompany_idGreaterThan(String value) {
            addCriterion("company_id >", value, "company_id");
            return (Criteria) this;
        }

        public Criteria andCompany_idGreaterThanOrEqualTo(String value) {
            addCriterion("company_id >=", value, "company_id");
            return (Criteria) this;
        }

        public Criteria andCompany_idLessThan(String value) {
            addCriterion("company_id <", value, "company_id");
            return (Criteria) this;
        }

        public Criteria andCompany_idLessThanOrEqualTo(String value) {
            addCriterion("company_id <=", value, "company_id");
            return (Criteria) this;
        }

        public Criteria andCompany_idLike(String value) {
            addCriterion("company_id like", value, "company_id");
            return (Criteria) this;
        }

        public Criteria andCompany_idNotLike(String value) {
            addCriterion("company_id not like", value, "company_id");
            return (Criteria) this;
        }

        public Criteria andCompany_idIn(List<String> values) {
            addCriterion("company_id in", values, "company_id");
            return (Criteria) this;
        }

        public Criteria andCompany_idNotIn(List<String> values) {
            addCriterion("company_id not in", values, "company_id");
            return (Criteria) this;
        }

        public Criteria andCompany_idBetween(String value1, String value2) {
            addCriterion("company_id between", value1, value2, "company_id");
            return (Criteria) this;
        }

        public Criteria andCompany_idNotBetween(String value1, String value2) {
            addCriterion("company_id not between", value1, value2, "company_id");
            return (Criteria) this;
        }

        public Criteria andBoat_codeIsNull() {
            addCriterion("boat_code is null");
            return (Criteria) this;
        }

        public Criteria andBoat_codeIsNotNull() {
            addCriterion("boat_code is not null");
            return (Criteria) this;
        }

        public Criteria andBoat_codeEqualTo(String value) {
            addCriterion("boat_code =", value, "boat_code");
            return (Criteria) this;
        }

        public Criteria andBoat_codeNotEqualTo(String value) {
            addCriterion("boat_code <>", value, "boat_code");
            return (Criteria) this;
        }

        public Criteria andBoat_codeGreaterThan(String value) {
            addCriterion("boat_code >", value, "boat_code");
            return (Criteria) this;
        }

        public Criteria andBoat_codeGreaterThanOrEqualTo(String value) {
            addCriterion("boat_code >=", value, "boat_code");
            return (Criteria) this;
        }

        public Criteria andBoat_codeLessThan(String value) {
            addCriterion("boat_code <", value, "boat_code");
            return (Criteria) this;
        }

        public Criteria andBoat_codeLessThanOrEqualTo(String value) {
            addCriterion("boat_code <=", value, "boat_code");
            return (Criteria) this;
        }

        public Criteria andBoat_codeLike(String value) {
            addCriterion("boat_code like", value, "boat_code");
            return (Criteria) this;
        }

        public Criteria andBoat_codeNotLike(String value) {
            addCriterion("boat_code not like", value, "boat_code");
            return (Criteria) this;
        }

        public Criteria andBoat_codeIn(List<String> values) {
            addCriterion("boat_code in", values, "boat_code");
            return (Criteria) this;
        }

        public Criteria andBoat_codeNotIn(List<String> values) {
            addCriterion("boat_code not in", values, "boat_code");
            return (Criteria) this;
        }

        public Criteria andBoat_codeBetween(String value1, String value2) {
            addCriterion("boat_code between", value1, value2, "boat_code");
            return (Criteria) this;
        }

        public Criteria andBoat_codeNotBetween(String value1, String value2) {
            addCriterion("boat_code not between", value1, value2, "boat_code");
            return (Criteria) this;
        }

        public Criteria andBoat_nameIsNull() {
            addCriterion("boat_name is null");
            return (Criteria) this;
        }

        public Criteria andBoat_nameIsNotNull() {
            addCriterion("boat_name is not null");
            return (Criteria) this;
        }

        public Criteria andBoat_nameEqualTo(String value) {
            addCriterion("boat_name =", value, "boat_name");
            return (Criteria) this;
        }

        public Criteria andBoat_nameNotEqualTo(String value) {
            addCriterion("boat_name <>", value, "boat_name");
            return (Criteria) this;
        }

        public Criteria andBoat_nameGreaterThan(String value) {
            addCriterion("boat_name >", value, "boat_name");
            return (Criteria) this;
        }

        public Criteria andBoat_nameGreaterThanOrEqualTo(String value) {
            addCriterion("boat_name >=", value, "boat_name");
            return (Criteria) this;
        }

        public Criteria andBoat_nameLessThan(String value) {
            addCriterion("boat_name <", value, "boat_name");
            return (Criteria) this;
        }

        public Criteria andBoat_nameLessThanOrEqualTo(String value) {
            addCriterion("boat_name <=", value, "boat_name");
            return (Criteria) this;
        }

        public Criteria andBoat_nameLike(String value) {
            addCriterion("boat_name like", value, "boat_name");
            return (Criteria) this;
        }

        public Criteria andBoat_nameNotLike(String value) {
            addCriterion("boat_name not like", value, "boat_name");
            return (Criteria) this;
        }

        public Criteria andBoat_nameIn(List<String> values) {
            addCriterion("boat_name in", values, "boat_name");
            return (Criteria) this;
        }

        public Criteria andBoat_nameNotIn(List<String> values) {
            addCriterion("boat_name not in", values, "boat_name");
            return (Criteria) this;
        }

        public Criteria andBoat_nameBetween(String value1, String value2) {
            addCriterion("boat_name between", value1, value2, "boat_name");
            return (Criteria) this;
        }

        public Criteria andBoat_nameNotBetween(String value1, String value2) {
            addCriterion("boat_name not between", value1, value2, "boat_name");
            return (Criteria) this;
        }

        public Criteria andFlag_countryIsNull() {
            addCriterion("flag_country is null");
            return (Criteria) this;
        }

        public Criteria andFlag_countryIsNotNull() {
            addCriterion("flag_country is not null");
            return (Criteria) this;
        }

        public Criteria andFlag_countryEqualTo(String value) {
            addCriterion("flag_country =", value, "flag_country");
            return (Criteria) this;
        }

        public Criteria andFlag_countryNotEqualTo(String value) {
            addCriterion("flag_country <>", value, "flag_country");
            return (Criteria) this;
        }

        public Criteria andFlag_countryGreaterThan(String value) {
            addCriterion("flag_country >", value, "flag_country");
            return (Criteria) this;
        }

        public Criteria andFlag_countryGreaterThanOrEqualTo(String value) {
            addCriterion("flag_country >=", value, "flag_country");
            return (Criteria) this;
        }

        public Criteria andFlag_countryLessThan(String value) {
            addCriterion("flag_country <", value, "flag_country");
            return (Criteria) this;
        }

        public Criteria andFlag_countryLessThanOrEqualTo(String value) {
            addCriterion("flag_country <=", value, "flag_country");
            return (Criteria) this;
        }

        public Criteria andFlag_countryLike(String value) {
            addCriterion("flag_country like", value, "flag_country");
            return (Criteria) this;
        }

        public Criteria andFlag_countryNotLike(String value) {
            addCriterion("flag_country not like", value, "flag_country");
            return (Criteria) this;
        }

        public Criteria andFlag_countryIn(List<String> values) {
            addCriterion("flag_country in", values, "flag_country");
            return (Criteria) this;
        }

        public Criteria andFlag_countryNotIn(List<String> values) {
            addCriterion("flag_country not in", values, "flag_country");
            return (Criteria) this;
        }

        public Criteria andFlag_countryBetween(String value1, String value2) {
            addCriterion("flag_country between", value1, value2, "flag_country");
            return (Criteria) this;
        }

        public Criteria andFlag_countryNotBetween(String value1, String value2) {
            addCriterion("flag_country not between", value1, value2, "flag_country");
            return (Criteria) this;
        }

        public Criteria andContactIsNull() {
            addCriterion("contact is null");
            return (Criteria) this;
        }

        public Criteria andContactIsNotNull() {
            addCriterion("contact is not null");
            return (Criteria) this;
        }

        public Criteria andContactEqualTo(String value) {
            addCriterion("contact =", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotEqualTo(String value) {
            addCriterion("contact <>", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactGreaterThan(String value) {
            addCriterion("contact >", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactGreaterThanOrEqualTo(String value) {
            addCriterion("contact >=", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactLessThan(String value) {
            addCriterion("contact <", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactLessThanOrEqualTo(String value) {
            addCriterion("contact <=", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactLike(String value) {
            addCriterion("contact like", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotLike(String value) {
            addCriterion("contact not like", value, "contact");
            return (Criteria) this;
        }

        public Criteria andContactIn(List<String> values) {
            addCriterion("contact in", values, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotIn(List<String> values) {
            addCriterion("contact not in", values, "contact");
            return (Criteria) this;
        }

        public Criteria andContactBetween(String value1, String value2) {
            addCriterion("contact between", value1, value2, "contact");
            return (Criteria) this;
        }

        public Criteria andContactNotBetween(String value1, String value2) {
            addCriterion("contact not between", value1, value2, "contact");
            return (Criteria) this;
        }

        public Criteria andContact_phoneIsNull() {
            addCriterion("contact_phone is null");
            return (Criteria) this;
        }

        public Criteria andContact_phoneIsNotNull() {
            addCriterion("contact_phone is not null");
            return (Criteria) this;
        }

        public Criteria andContact_phoneEqualTo(String value) {
            addCriterion("contact_phone =", value, "contact_phone");
            return (Criteria) this;
        }

        public Criteria andContact_phoneNotEqualTo(String value) {
            addCriterion("contact_phone <>", value, "contact_phone");
            return (Criteria) this;
        }

        public Criteria andContact_phoneGreaterThan(String value) {
            addCriterion("contact_phone >", value, "contact_phone");
            return (Criteria) this;
        }

        public Criteria andContact_phoneGreaterThanOrEqualTo(String value) {
            addCriterion("contact_phone >=", value, "contact_phone");
            return (Criteria) this;
        }

        public Criteria andContact_phoneLessThan(String value) {
            addCriterion("contact_phone <", value, "contact_phone");
            return (Criteria) this;
        }

        public Criteria andContact_phoneLessThanOrEqualTo(String value) {
            addCriterion("contact_phone <=", value, "contact_phone");
            return (Criteria) this;
        }

        public Criteria andContact_phoneLike(String value) {
            addCriterion("contact_phone like", value, "contact_phone");
            return (Criteria) this;
        }

        public Criteria andContact_phoneNotLike(String value) {
            addCriterion("contact_phone not like", value, "contact_phone");
            return (Criteria) this;
        }

        public Criteria andContact_phoneIn(List<String> values) {
            addCriterion("contact_phone in", values, "contact_phone");
            return (Criteria) this;
        }

        public Criteria andContact_phoneNotIn(List<String> values) {
            addCriterion("contact_phone not in", values, "contact_phone");
            return (Criteria) this;
        }

        public Criteria andContact_phoneBetween(String value1, String value2) {
            addCriterion("contact_phone between", value1, value2, "contact_phone");
            return (Criteria) this;
        }

        public Criteria andContact_phoneNotBetween(String value1, String value2) {
            addCriterion("contact_phone not between", value1, value2, "contact_phone");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andBoat_lengthIsNull() {
            addCriterion("boat_length is null");
            return (Criteria) this;
        }

        public Criteria andBoat_lengthIsNotNull() {
            addCriterion("boat_length is not null");
            return (Criteria) this;
        }

        public Criteria andBoat_lengthEqualTo(BigDecimal value) {
            addCriterion("boat_length =", value, "boat_length");
            return (Criteria) this;
        }

        public Criteria andBoat_lengthNotEqualTo(BigDecimal value) {
            addCriterion("boat_length <>", value, "boat_length");
            return (Criteria) this;
        }

        public Criteria andBoat_lengthGreaterThan(BigDecimal value) {
            addCriterion("boat_length >", value, "boat_length");
            return (Criteria) this;
        }

        public Criteria andBoat_lengthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("boat_length >=", value, "boat_length");
            return (Criteria) this;
        }

        public Criteria andBoat_lengthLessThan(BigDecimal value) {
            addCriterion("boat_length <", value, "boat_length");
            return (Criteria) this;
        }

        public Criteria andBoat_lengthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("boat_length <=", value, "boat_length");
            return (Criteria) this;
        }

        public Criteria andBoat_lengthIn(List<BigDecimal> values) {
            addCriterion("boat_length in", values, "boat_length");
            return (Criteria) this;
        }

        public Criteria andBoat_lengthNotIn(List<BigDecimal> values) {
            addCriterion("boat_length not in", values, "boat_length");
            return (Criteria) this;
        }

        public Criteria andBoat_lengthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("boat_length between", value1, value2, "boat_length");
            return (Criteria) this;
        }

        public Criteria andBoat_lengthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("boat_length not between", value1, value2, "boat_length");
            return (Criteria) this;
        }

        public Criteria andBoat_widthIsNull() {
            addCriterion("boat_width is null");
            return (Criteria) this;
        }

        public Criteria andBoat_widthIsNotNull() {
            addCriterion("boat_width is not null");
            return (Criteria) this;
        }

        public Criteria andBoat_widthEqualTo(BigDecimal value) {
            addCriterion("boat_width =", value, "boat_width");
            return (Criteria) this;
        }

        public Criteria andBoat_widthNotEqualTo(BigDecimal value) {
            addCriterion("boat_width <>", value, "boat_width");
            return (Criteria) this;
        }

        public Criteria andBoat_widthGreaterThan(BigDecimal value) {
            addCriterion("boat_width >", value, "boat_width");
            return (Criteria) this;
        }

        public Criteria andBoat_widthGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("boat_width >=", value, "boat_width");
            return (Criteria) this;
        }

        public Criteria andBoat_widthLessThan(BigDecimal value) {
            addCriterion("boat_width <", value, "boat_width");
            return (Criteria) this;
        }

        public Criteria andBoat_widthLessThanOrEqualTo(BigDecimal value) {
            addCriterion("boat_width <=", value, "boat_width");
            return (Criteria) this;
        }

        public Criteria andBoat_widthIn(List<BigDecimal> values) {
            addCriterion("boat_width in", values, "boat_width");
            return (Criteria) this;
        }

        public Criteria andBoat_widthNotIn(List<BigDecimal> values) {
            addCriterion("boat_width not in", values, "boat_width");
            return (Criteria) this;
        }

        public Criteria andBoat_widthBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("boat_width between", value1, value2, "boat_width");
            return (Criteria) this;
        }

        public Criteria andBoat_widthNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("boat_width not between", value1, value2, "boat_width");
            return (Criteria) this;
        }

        public Criteria andBoat_heightIsNull() {
            addCriterion("boat_height is null");
            return (Criteria) this;
        }

        public Criteria andBoat_heightIsNotNull() {
            addCriterion("boat_height is not null");
            return (Criteria) this;
        }

        public Criteria andBoat_heightEqualTo(BigDecimal value) {
            addCriterion("boat_height =", value, "boat_height");
            return (Criteria) this;
        }

        public Criteria andBoat_heightNotEqualTo(BigDecimal value) {
            addCriterion("boat_height <>", value, "boat_height");
            return (Criteria) this;
        }

        public Criteria andBoat_heightGreaterThan(BigDecimal value) {
            addCriterion("boat_height >", value, "boat_height");
            return (Criteria) this;
        }

        public Criteria andBoat_heightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("boat_height >=", value, "boat_height");
            return (Criteria) this;
        }

        public Criteria andBoat_heightLessThan(BigDecimal value) {
            addCriterion("boat_height <", value, "boat_height");
            return (Criteria) this;
        }

        public Criteria andBoat_heightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("boat_height <=", value, "boat_height");
            return (Criteria) this;
        }

        public Criteria andBoat_heightIn(List<BigDecimal> values) {
            addCriterion("boat_height in", values, "boat_height");
            return (Criteria) this;
        }

        public Criteria andBoat_heightNotIn(List<BigDecimal> values) {
            addCriterion("boat_height not in", values, "boat_height");
            return (Criteria) this;
        }

        public Criteria andBoat_heightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("boat_height between", value1, value2, "boat_height");
            return (Criteria) this;
        }

        public Criteria andBoat_heightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("boat_height not between", value1, value2, "boat_height");
            return (Criteria) this;
        }

        public Criteria andDraftIsNull() {
            addCriterion("draft is null");
            return (Criteria) this;
        }

        public Criteria andDraftIsNotNull() {
            addCriterion("draft is not null");
            return (Criteria) this;
        }

        public Criteria andDraftEqualTo(BigDecimal value) {
            addCriterion("draft =", value, "draft");
            return (Criteria) this;
        }

        public Criteria andDraftNotEqualTo(BigDecimal value) {
            addCriterion("draft <>", value, "draft");
            return (Criteria) this;
        }

        public Criteria andDraftGreaterThan(BigDecimal value) {
            addCriterion("draft >", value, "draft");
            return (Criteria) this;
        }

        public Criteria andDraftGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("draft >=", value, "draft");
            return (Criteria) this;
        }

        public Criteria andDraftLessThan(BigDecimal value) {
            addCriterion("draft <", value, "draft");
            return (Criteria) this;
        }

        public Criteria andDraftLessThanOrEqualTo(BigDecimal value) {
            addCriterion("draft <=", value, "draft");
            return (Criteria) this;
        }

        public Criteria andDraftIn(List<BigDecimal> values) {
            addCriterion("draft in", values, "draft");
            return (Criteria) this;
        }

        public Criteria andDraftNotIn(List<BigDecimal> values) {
            addCriterion("draft not in", values, "draft");
            return (Criteria) this;
        }

        public Criteria andDraftBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("draft between", value1, value2, "draft");
            return (Criteria) this;
        }

        public Criteria andDraftNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("draft not between", value1, value2, "draft");
            return (Criteria) this;
        }

        public Criteria andDead_weightIsNull() {
            addCriterion("dead_weight is null");
            return (Criteria) this;
        }

        public Criteria andDead_weightIsNotNull() {
            addCriterion("dead_weight is not null");
            return (Criteria) this;
        }

        public Criteria andDead_weightEqualTo(BigDecimal value) {
            addCriterion("dead_weight =", value, "dead_weight");
            return (Criteria) this;
        }

        public Criteria andDead_weightNotEqualTo(BigDecimal value) {
            addCriterion("dead_weight <>", value, "dead_weight");
            return (Criteria) this;
        }

        public Criteria andDead_weightGreaterThan(BigDecimal value) {
            addCriterion("dead_weight >", value, "dead_weight");
            return (Criteria) this;
        }

        public Criteria andDead_weightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("dead_weight >=", value, "dead_weight");
            return (Criteria) this;
        }

        public Criteria andDead_weightLessThan(BigDecimal value) {
            addCriterion("dead_weight <", value, "dead_weight");
            return (Criteria) this;
        }

        public Criteria andDead_weightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("dead_weight <=", value, "dead_weight");
            return (Criteria) this;
        }

        public Criteria andDead_weightIn(List<BigDecimal> values) {
            addCriterion("dead_weight in", values, "dead_weight");
            return (Criteria) this;
        }

        public Criteria andDead_weightNotIn(List<BigDecimal> values) {
            addCriterion("dead_weight not in", values, "dead_weight");
            return (Criteria) this;
        }

        public Criteria andDead_weightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dead_weight between", value1, value2, "dead_weight");
            return (Criteria) this;
        }

        public Criteria andDead_weightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("dead_weight not between", value1, value2, "dead_weight");
            return (Criteria) this;
        }

        public Criteria andNet_dead_weightIsNull() {
            addCriterion("net_dead_weight is null");
            return (Criteria) this;
        }

        public Criteria andNet_dead_weightIsNotNull() {
            addCriterion("net_dead_weight is not null");
            return (Criteria) this;
        }

        public Criteria andNet_dead_weightEqualTo(BigDecimal value) {
            addCriterion("net_dead_weight =", value, "net_dead_weight");
            return (Criteria) this;
        }

        public Criteria andNet_dead_weightNotEqualTo(BigDecimal value) {
            addCriterion("net_dead_weight <>", value, "net_dead_weight");
            return (Criteria) this;
        }

        public Criteria andNet_dead_weightGreaterThan(BigDecimal value) {
            addCriterion("net_dead_weight >", value, "net_dead_weight");
            return (Criteria) this;
        }

        public Criteria andNet_dead_weightGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("net_dead_weight >=", value, "net_dead_weight");
            return (Criteria) this;
        }

        public Criteria andNet_dead_weightLessThan(BigDecimal value) {
            addCriterion("net_dead_weight <", value, "net_dead_weight");
            return (Criteria) this;
        }

        public Criteria andNet_dead_weightLessThanOrEqualTo(BigDecimal value) {
            addCriterion("net_dead_weight <=", value, "net_dead_weight");
            return (Criteria) this;
        }

        public Criteria andNet_dead_weightIn(List<BigDecimal> values) {
            addCriterion("net_dead_weight in", values, "net_dead_weight");
            return (Criteria) this;
        }

        public Criteria andNet_dead_weightNotIn(List<BigDecimal> values) {
            addCriterion("net_dead_weight not in", values, "net_dead_weight");
            return (Criteria) this;
        }

        public Criteria andNet_dead_weightBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("net_dead_weight between", value1, value2, "net_dead_weight");
            return (Criteria) this;
        }

        public Criteria andNet_dead_weightNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("net_dead_weight not between", value1, value2, "net_dead_weight");
            return (Criteria) this;
        }

        public Criteria andCapacityIsNull() {
            addCriterion("capacity is null");
            return (Criteria) this;
        }

        public Criteria andCapacityIsNotNull() {
            addCriterion("capacity is not null");
            return (Criteria) this;
        }

        public Criteria andCapacityEqualTo(BigDecimal value) {
            addCriterion("capacity =", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotEqualTo(BigDecimal value) {
            addCriterion("capacity <>", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityGreaterThan(BigDecimal value) {
            addCriterion("capacity >", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("capacity >=", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityLessThan(BigDecimal value) {
            addCriterion("capacity <", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("capacity <=", value, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityIn(List<BigDecimal> values) {
            addCriterion("capacity in", values, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotIn(List<BigDecimal> values) {
            addCriterion("capacity not in", values, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("capacity between", value1, value2, "capacity");
            return (Criteria) this;
        }

        public Criteria andCapacityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("capacity not between", value1, value2, "capacity");
            return (Criteria) this;
        }

        public Criteria andNet_capacitIsNull() {
            addCriterion("net_capacit is null");
            return (Criteria) this;
        }

        public Criteria andNet_capacitIsNotNull() {
            addCriterion("net_capacit is not null");
            return (Criteria) this;
        }

        public Criteria andNet_capacitEqualTo(BigDecimal value) {
            addCriterion("net_capacit =", value, "net_capacit");
            return (Criteria) this;
        }

        public Criteria andNet_capacitNotEqualTo(BigDecimal value) {
            addCriterion("net_capacit <>", value, "net_capacit");
            return (Criteria) this;
        }

        public Criteria andNet_capacitGreaterThan(BigDecimal value) {
            addCriterion("net_capacit >", value, "net_capacit");
            return (Criteria) this;
        }

        public Criteria andNet_capacitGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("net_capacit >=", value, "net_capacit");
            return (Criteria) this;
        }

        public Criteria andNet_capacitLessThan(BigDecimal value) {
            addCriterion("net_capacit <", value, "net_capacit");
            return (Criteria) this;
        }

        public Criteria andNet_capacitLessThanOrEqualTo(BigDecimal value) {
            addCriterion("net_capacit <=", value, "net_capacit");
            return (Criteria) this;
        }

        public Criteria andNet_capacitIn(List<BigDecimal> values) {
            addCriterion("net_capacit in", values, "net_capacit");
            return (Criteria) this;
        }

        public Criteria andNet_capacitNotIn(List<BigDecimal> values) {
            addCriterion("net_capacit not in", values, "net_capacit");
            return (Criteria) this;
        }

        public Criteria andNet_capacitBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("net_capacit between", value1, value2, "net_capacit");
            return (Criteria) this;
        }

        public Criteria andNet_capacitNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("net_capacit not between", value1, value2, "net_capacit");
            return (Criteria) this;
        }

        public Criteria andBulk_capacityIsNull() {
            addCriterion("bulk_capacity is null");
            return (Criteria) this;
        }

        public Criteria andBulk_capacityIsNotNull() {
            addCriterion("bulk_capacity is not null");
            return (Criteria) this;
        }

        public Criteria andBulk_capacityEqualTo(BigDecimal value) {
            addCriterion("bulk_capacity =", value, "bulk_capacity");
            return (Criteria) this;
        }

        public Criteria andBulk_capacityNotEqualTo(BigDecimal value) {
            addCriterion("bulk_capacity <>", value, "bulk_capacity");
            return (Criteria) this;
        }

        public Criteria andBulk_capacityGreaterThan(BigDecimal value) {
            addCriterion("bulk_capacity >", value, "bulk_capacity");
            return (Criteria) this;
        }

        public Criteria andBulk_capacityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bulk_capacity >=", value, "bulk_capacity");
            return (Criteria) this;
        }

        public Criteria andBulk_capacityLessThan(BigDecimal value) {
            addCriterion("bulk_capacity <", value, "bulk_capacity");
            return (Criteria) this;
        }

        public Criteria andBulk_capacityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bulk_capacity <=", value, "bulk_capacity");
            return (Criteria) this;
        }

        public Criteria andBulk_capacityIn(List<BigDecimal> values) {
            addCriterion("bulk_capacity in", values, "bulk_capacity");
            return (Criteria) this;
        }

        public Criteria andBulk_capacityNotIn(List<BigDecimal> values) {
            addCriterion("bulk_capacity not in", values, "bulk_capacity");
            return (Criteria) this;
        }

        public Criteria andBulk_capacityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bulk_capacity between", value1, value2, "bulk_capacity");
            return (Criteria) this;
        }

        public Criteria andBulk_capacityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bulk_capacity not between", value1, value2, "bulk_capacity");
            return (Criteria) this;
        }

        public Criteria andBale_capacityIsNull() {
            addCriterion("bale_capacity is null");
            return (Criteria) this;
        }

        public Criteria andBale_capacityIsNotNull() {
            addCriterion("bale_capacity is not null");
            return (Criteria) this;
        }

        public Criteria andBale_capacityEqualTo(BigDecimal value) {
            addCriterion("bale_capacity =", value, "bale_capacity");
            return (Criteria) this;
        }

        public Criteria andBale_capacityNotEqualTo(BigDecimal value) {
            addCriterion("bale_capacity <>", value, "bale_capacity");
            return (Criteria) this;
        }

        public Criteria andBale_capacityGreaterThan(BigDecimal value) {
            addCriterion("bale_capacity >", value, "bale_capacity");
            return (Criteria) this;
        }

        public Criteria andBale_capacityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("bale_capacity >=", value, "bale_capacity");
            return (Criteria) this;
        }

        public Criteria andBale_capacityLessThan(BigDecimal value) {
            addCriterion("bale_capacity <", value, "bale_capacity");
            return (Criteria) this;
        }

        public Criteria andBale_capacityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("bale_capacity <=", value, "bale_capacity");
            return (Criteria) this;
        }

        public Criteria andBale_capacityIn(List<BigDecimal> values) {
            addCriterion("bale_capacity in", values, "bale_capacity");
            return (Criteria) this;
        }

        public Criteria andBale_capacityNotIn(List<BigDecimal> values) {
            addCriterion("bale_capacity not in", values, "bale_capacity");
            return (Criteria) this;
        }

        public Criteria andBale_capacityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bale_capacity between", value1, value2, "bale_capacity");
            return (Criteria) this;
        }

        public Criteria andBale_capacityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("bale_capacity not between", value1, value2, "bale_capacity");
            return (Criteria) this;
        }

        public Criteria andHatch_sizeIsNull() {
            addCriterion("hatch_size is null");
            return (Criteria) this;
        }

        public Criteria andHatch_sizeIsNotNull() {
            addCriterion("hatch_size is not null");
            return (Criteria) this;
        }

        public Criteria andHatch_sizeEqualTo(BigDecimal value) {
            addCriterion("hatch_size =", value, "hatch_size");
            return (Criteria) this;
        }

        public Criteria andHatch_sizeNotEqualTo(BigDecimal value) {
            addCriterion("hatch_size <>", value, "hatch_size");
            return (Criteria) this;
        }

        public Criteria andHatch_sizeGreaterThan(BigDecimal value) {
            addCriterion("hatch_size >", value, "hatch_size");
            return (Criteria) this;
        }

        public Criteria andHatch_sizeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("hatch_size >=", value, "hatch_size");
            return (Criteria) this;
        }

        public Criteria andHatch_sizeLessThan(BigDecimal value) {
            addCriterion("hatch_size <", value, "hatch_size");
            return (Criteria) this;
        }

        public Criteria andHatch_sizeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("hatch_size <=", value, "hatch_size");
            return (Criteria) this;
        }

        public Criteria andHatch_sizeIn(List<BigDecimal> values) {
            addCriterion("hatch_size in", values, "hatch_size");
            return (Criteria) this;
        }

        public Criteria andHatch_sizeNotIn(List<BigDecimal> values) {
            addCriterion("hatch_size not in", values, "hatch_size");
            return (Criteria) this;
        }

        public Criteria andHatch_sizeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hatch_size between", value1, value2, "hatch_size");
            return (Criteria) this;
        }

        public Criteria andHatch_sizeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("hatch_size not between", value1, value2, "hatch_size");
            return (Criteria) this;
        }

        public Criteria andSpeedIsNull() {
            addCriterion("speed is null");
            return (Criteria) this;
        }

        public Criteria andSpeedIsNotNull() {
            addCriterion("speed is not null");
            return (Criteria) this;
        }

        public Criteria andSpeedEqualTo(BigDecimal value) {
            addCriterion("speed =", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedNotEqualTo(BigDecimal value) {
            addCriterion("speed <>", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedGreaterThan(BigDecimal value) {
            addCriterion("speed >", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("speed >=", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedLessThan(BigDecimal value) {
            addCriterion("speed <", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedLessThanOrEqualTo(BigDecimal value) {
            addCriterion("speed <=", value, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedIn(List<BigDecimal> values) {
            addCriterion("speed in", values, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedNotIn(List<BigDecimal> values) {
            addCriterion("speed not in", values, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("speed between", value1, value2, "speed");
            return (Criteria) this;
        }

        public Criteria andSpeedNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("speed not between", value1, value2, "speed");
            return (Criteria) this;
        }

        public Criteria andBoat_classIsNull() {
            addCriterion("boat_class is null");
            return (Criteria) this;
        }

        public Criteria andBoat_classIsNotNull() {
            addCriterion("boat_class is not null");
            return (Criteria) this;
        }

        public Criteria andBoat_classEqualTo(String value) {
            addCriterion("boat_class =", value, "boat_class");
            return (Criteria) this;
        }

        public Criteria andBoat_classNotEqualTo(String value) {
            addCriterion("boat_class <>", value, "boat_class");
            return (Criteria) this;
        }

        public Criteria andBoat_classGreaterThan(String value) {
            addCriterion("boat_class >", value, "boat_class");
            return (Criteria) this;
        }

        public Criteria andBoat_classGreaterThanOrEqualTo(String value) {
            addCriterion("boat_class >=", value, "boat_class");
            return (Criteria) this;
        }

        public Criteria andBoat_classLessThan(String value) {
            addCriterion("boat_class <", value, "boat_class");
            return (Criteria) this;
        }

        public Criteria andBoat_classLessThanOrEqualTo(String value) {
            addCriterion("boat_class <=", value, "boat_class");
            return (Criteria) this;
        }

        public Criteria andBoat_classLike(String value) {
            addCriterion("boat_class like", value, "boat_class");
            return (Criteria) this;
        }

        public Criteria andBoat_classNotLike(String value) {
            addCriterion("boat_class not like", value, "boat_class");
            return (Criteria) this;
        }

        public Criteria andBoat_classIn(List<String> values) {
            addCriterion("boat_class in", values, "boat_class");
            return (Criteria) this;
        }

        public Criteria andBoat_classNotIn(List<String> values) {
            addCriterion("boat_class not in", values, "boat_class");
            return (Criteria) this;
        }

        public Criteria andBoat_classBetween(String value1, String value2) {
            addCriterion("boat_class between", value1, value2, "boat_class");
            return (Criteria) this;
        }

        public Criteria andBoat_classNotBetween(String value1, String value2) {
            addCriterion("boat_class not between", value1, value2, "boat_class");
            return (Criteria) this;
        }

        public Criteria andImoIsNull() {
            addCriterion("imo is null");
            return (Criteria) this;
        }

        public Criteria andImoIsNotNull() {
            addCriterion("imo is not null");
            return (Criteria) this;
        }

        public Criteria andImoEqualTo(String value) {
            addCriterion("imo =", value, "imo");
            return (Criteria) this;
        }

        public Criteria andImoNotEqualTo(String value) {
            addCriterion("imo <>", value, "imo");
            return (Criteria) this;
        }

        public Criteria andImoGreaterThan(String value) {
            addCriterion("imo >", value, "imo");
            return (Criteria) this;
        }

        public Criteria andImoGreaterThanOrEqualTo(String value) {
            addCriterion("imo >=", value, "imo");
            return (Criteria) this;
        }

        public Criteria andImoLessThan(String value) {
            addCriterion("imo <", value, "imo");
            return (Criteria) this;
        }

        public Criteria andImoLessThanOrEqualTo(String value) {
            addCriterion("imo <=", value, "imo");
            return (Criteria) this;
        }

        public Criteria andImoLike(String value) {
            addCriterion("imo like", value, "imo");
            return (Criteria) this;
        }

        public Criteria andImoNotLike(String value) {
            addCriterion("imo not like", value, "imo");
            return (Criteria) this;
        }

        public Criteria andImoIn(List<String> values) {
            addCriterion("imo in", values, "imo");
            return (Criteria) this;
        }

        public Criteria andImoNotIn(List<String> values) {
            addCriterion("imo not in", values, "imo");
            return (Criteria) this;
        }

        public Criteria andImoBetween(String value1, String value2) {
            addCriterion("imo between", value1, value2, "imo");
            return (Criteria) this;
        }

        public Criteria andImoNotBetween(String value1, String value2) {
            addCriterion("imo not between", value1, value2, "imo");
            return (Criteria) this;
        }

        public Criteria andCraneIsNull() {
            addCriterion("crane is null");
            return (Criteria) this;
        }

        public Criteria andCraneIsNotNull() {
            addCriterion("crane is not null");
            return (Criteria) this;
        }

        public Criteria andCraneEqualTo(String value) {
            addCriterion("crane =", value, "crane");
            return (Criteria) this;
        }

        public Criteria andCraneNotEqualTo(String value) {
            addCriterion("crane <>", value, "crane");
            return (Criteria) this;
        }

        public Criteria andCraneGreaterThan(String value) {
            addCriterion("crane >", value, "crane");
            return (Criteria) this;
        }

        public Criteria andCraneGreaterThanOrEqualTo(String value) {
            addCriterion("crane >=", value, "crane");
            return (Criteria) this;
        }

        public Criteria andCraneLessThan(String value) {
            addCriterion("crane <", value, "crane");
            return (Criteria) this;
        }

        public Criteria andCraneLessThanOrEqualTo(String value) {
            addCriterion("crane <=", value, "crane");
            return (Criteria) this;
        }

        public Criteria andCraneLike(String value) {
            addCriterion("crane like", value, "crane");
            return (Criteria) this;
        }

        public Criteria andCraneNotLike(String value) {
            addCriterion("crane not like", value, "crane");
            return (Criteria) this;
        }

        public Criteria andCraneIn(List<String> values) {
            addCriterion("crane in", values, "crane");
            return (Criteria) this;
        }

        public Criteria andCraneNotIn(List<String> values) {
            addCriterion("crane not in", values, "crane");
            return (Criteria) this;
        }

        public Criteria andCraneBetween(String value1, String value2) {
            addCriterion("crane between", value1, value2, "crane");
            return (Criteria) this;
        }

        public Criteria andCraneNotBetween(String value1, String value2) {
            addCriterion("crane not between", value1, value2, "crane");
            return (Criteria) this;
        }

        public Criteria andMmsiIsNull() {
            addCriterion("mmsi is null");
            return (Criteria) this;
        }

        public Criteria andMmsiIsNotNull() {
            addCriterion("mmsi is not null");
            return (Criteria) this;
        }

        public Criteria andMmsiEqualTo(String value) {
            addCriterion("mmsi =", value, "mmsi");
            return (Criteria) this;
        }

        public Criteria andMmsiNotEqualTo(String value) {
            addCriterion("mmsi <>", value, "mmsi");
            return (Criteria) this;
        }

        public Criteria andMmsiGreaterThan(String value) {
            addCriterion("mmsi >", value, "mmsi");
            return (Criteria) this;
        }

        public Criteria andMmsiGreaterThanOrEqualTo(String value) {
            addCriterion("mmsi >=", value, "mmsi");
            return (Criteria) this;
        }

        public Criteria andMmsiLessThan(String value) {
            addCriterion("mmsi <", value, "mmsi");
            return (Criteria) this;
        }

        public Criteria andMmsiLessThanOrEqualTo(String value) {
            addCriterion("mmsi <=", value, "mmsi");
            return (Criteria) this;
        }

        public Criteria andMmsiLike(String value) {
            addCriterion("mmsi like", value, "mmsi");
            return (Criteria) this;
        }

        public Criteria andMmsiNotLike(String value) {
            addCriterion("mmsi not like", value, "mmsi");
            return (Criteria) this;
        }

        public Criteria andMmsiIn(List<String> values) {
            addCriterion("mmsi in", values, "mmsi");
            return (Criteria) this;
        }

        public Criteria andMmsiNotIn(List<String> values) {
            addCriterion("mmsi not in", values, "mmsi");
            return (Criteria) this;
        }

        public Criteria andMmsiBetween(String value1, String value2) {
            addCriterion("mmsi between", value1, value2, "mmsi");
            return (Criteria) this;
        }

        public Criteria andMmsiNotBetween(String value1, String value2) {
            addCriterion("mmsi not between", value1, value2, "mmsi");
            return (Criteria) this;
        }

        public Criteria andGps_noIsNull() {
            addCriterion("gps_no is null");
            return (Criteria) this;
        }

        public Criteria andGps_noIsNotNull() {
            addCriterion("gps_no is not null");
            return (Criteria) this;
        }

        public Criteria andGps_noEqualTo(String value) {
            addCriterion("gps_no =", value, "gps_no");
            return (Criteria) this;
        }

        public Criteria andGps_noNotEqualTo(String value) {
            addCriterion("gps_no <>", value, "gps_no");
            return (Criteria) this;
        }

        public Criteria andGps_noGreaterThan(String value) {
            addCriterion("gps_no >", value, "gps_no");
            return (Criteria) this;
        }

        public Criteria andGps_noGreaterThanOrEqualTo(String value) {
            addCriterion("gps_no >=", value, "gps_no");
            return (Criteria) this;
        }

        public Criteria andGps_noLessThan(String value) {
            addCriterion("gps_no <", value, "gps_no");
            return (Criteria) this;
        }

        public Criteria andGps_noLessThanOrEqualTo(String value) {
            addCriterion("gps_no <=", value, "gps_no");
            return (Criteria) this;
        }

        public Criteria andGps_noLike(String value) {
            addCriterion("gps_no like", value, "gps_no");
            return (Criteria) this;
        }

        public Criteria andGps_noNotLike(String value) {
            addCriterion("gps_no not like", value, "gps_no");
            return (Criteria) this;
        }

        public Criteria andGps_noIn(List<String> values) {
            addCriterion("gps_no in", values, "gps_no");
            return (Criteria) this;
        }

        public Criteria andGps_noNotIn(List<String> values) {
            addCriterion("gps_no not in", values, "gps_no");
            return (Criteria) this;
        }

        public Criteria andGps_noBetween(String value1, String value2) {
            addCriterion("gps_no between", value1, value2, "gps_no");
            return (Criteria) this;
        }

        public Criteria andGps_noNotBetween(String value1, String value2) {
            addCriterion("gps_no not between", value1, value2, "gps_no");
            return (Criteria) this;
        }

        public Criteria andBuild_dateIsNull() {
            addCriterion("build_date is null");
            return (Criteria) this;
        }

        public Criteria andBuild_dateIsNotNull() {
            addCriterion("build_date is not null");
            return (Criteria) this;
        }

        public Criteria andBuild_dateEqualTo(String value) {
            addCriterion("build_date =", value, "build_date");
            return (Criteria) this;
        }

        public Criteria andBuild_dateNotEqualTo(String value) {
            addCriterion("build_date <>", value, "build_date");
            return (Criteria) this;
        }

        public Criteria andBuild_dateGreaterThan(String value) {
            addCriterion("build_date >", value, "build_date");
            return (Criteria) this;
        }

        public Criteria andBuild_dateGreaterThanOrEqualTo(String value) {
            addCriterion("build_date >=", value, "build_date");
            return (Criteria) this;
        }

        public Criteria andBuild_dateLessThan(String value) {
            addCriterion("build_date <", value, "build_date");
            return (Criteria) this;
        }

        public Criteria andBuild_dateLessThanOrEqualTo(String value) {
            addCriterion("build_date <=", value, "build_date");
            return (Criteria) this;
        }

        public Criteria andBuild_dateLike(String value) {
            addCriterion("build_date like", value, "build_date");
            return (Criteria) this;
        }

        public Criteria andBuild_dateNotLike(String value) {
            addCriterion("build_date not like", value, "build_date");
            return (Criteria) this;
        }

        public Criteria andBuild_dateIn(List<String> values) {
            addCriterion("build_date in", values, "build_date");
            return (Criteria) this;
        }

        public Criteria andBuild_dateNotIn(List<String> values) {
            addCriterion("build_date not in", values, "build_date");
            return (Criteria) this;
        }

        public Criteria andBuild_dateBetween(String value1, String value2) {
            addCriterion("build_date between", value1, value2, "build_date");
            return (Criteria) this;
        }

        public Criteria andBuild_dateNotBetween(String value1, String value2) {
            addCriterion("build_date not between", value1, value2, "build_date");
            return (Criteria) this;
        }

        public Criteria andBoat_phoneIsNull() {
            addCriterion("boat_phone is null");
            return (Criteria) this;
        }

        public Criteria andBoat_phoneIsNotNull() {
            addCriterion("boat_phone is not null");
            return (Criteria) this;
        }

        public Criteria andBoat_phoneEqualTo(String value) {
            addCriterion("boat_phone =", value, "boat_phone");
            return (Criteria) this;
        }

        public Criteria andBoat_phoneNotEqualTo(String value) {
            addCriterion("boat_phone <>", value, "boat_phone");
            return (Criteria) this;
        }

        public Criteria andBoat_phoneGreaterThan(String value) {
            addCriterion("boat_phone >", value, "boat_phone");
            return (Criteria) this;
        }

        public Criteria andBoat_phoneGreaterThanOrEqualTo(String value) {
            addCriterion("boat_phone >=", value, "boat_phone");
            return (Criteria) this;
        }

        public Criteria andBoat_phoneLessThan(String value) {
            addCriterion("boat_phone <", value, "boat_phone");
            return (Criteria) this;
        }

        public Criteria andBoat_phoneLessThanOrEqualTo(String value) {
            addCriterion("boat_phone <=", value, "boat_phone");
            return (Criteria) this;
        }

        public Criteria andBoat_phoneLike(String value) {
            addCriterion("boat_phone like", value, "boat_phone");
            return (Criteria) this;
        }

        public Criteria andBoat_phoneNotLike(String value) {
            addCriterion("boat_phone not like", value, "boat_phone");
            return (Criteria) this;
        }

        public Criteria andBoat_phoneIn(List<String> values) {
            addCriterion("boat_phone in", values, "boat_phone");
            return (Criteria) this;
        }

        public Criteria andBoat_phoneNotIn(List<String> values) {
            addCriterion("boat_phone not in", values, "boat_phone");
            return (Criteria) this;
        }

        public Criteria andBoat_phoneBetween(String value1, String value2) {
            addCriterion("boat_phone between", value1, value2, "boat_phone");
            return (Criteria) this;
        }

        public Criteria andBoat_phoneNotBetween(String value1, String value2) {
            addCriterion("boat_phone not between", value1, value2, "boat_phone");
            return (Criteria) this;
        }

        public Criteria andBoat_ownerIsNull() {
            addCriterion("boat_owner is null");
            return (Criteria) this;
        }

        public Criteria andBoat_ownerIsNotNull() {
            addCriterion("boat_owner is not null");
            return (Criteria) this;
        }

        public Criteria andBoat_ownerEqualTo(String value) {
            addCriterion("boat_owner =", value, "boat_owner");
            return (Criteria) this;
        }

        public Criteria andBoat_ownerNotEqualTo(String value) {
            addCriterion("boat_owner <>", value, "boat_owner");
            return (Criteria) this;
        }

        public Criteria andBoat_ownerGreaterThan(String value) {
            addCriterion("boat_owner >", value, "boat_owner");
            return (Criteria) this;
        }

        public Criteria andBoat_ownerGreaterThanOrEqualTo(String value) {
            addCriterion("boat_owner >=", value, "boat_owner");
            return (Criteria) this;
        }

        public Criteria andBoat_ownerLessThan(String value) {
            addCriterion("boat_owner <", value, "boat_owner");
            return (Criteria) this;
        }

        public Criteria andBoat_ownerLessThanOrEqualTo(String value) {
            addCriterion("boat_owner <=", value, "boat_owner");
            return (Criteria) this;
        }

        public Criteria andBoat_ownerLike(String value) {
            addCriterion("boat_owner like", value, "boat_owner");
            return (Criteria) this;
        }

        public Criteria andBoat_ownerNotLike(String value) {
            addCriterion("boat_owner not like", value, "boat_owner");
            return (Criteria) this;
        }

        public Criteria andBoat_ownerIn(List<String> values) {
            addCriterion("boat_owner in", values, "boat_owner");
            return (Criteria) this;
        }

        public Criteria andBoat_ownerNotIn(List<String> values) {
            addCriterion("boat_owner not in", values, "boat_owner");
            return (Criteria) this;
        }

        public Criteria andBoat_ownerBetween(String value1, String value2) {
            addCriterion("boat_owner between", value1, value2, "boat_owner");
            return (Criteria) this;
        }

        public Criteria andBoat_ownerNotBetween(String value1, String value2) {
            addCriterion("boat_owner not between", value1, value2, "boat_owner");
            return (Criteria) this;
        }

        public Criteria andPi_cert_urlIsNull() {
            addCriterion("pi_cert_url is null");
            return (Criteria) this;
        }

        public Criteria andPi_cert_urlIsNotNull() {
            addCriterion("pi_cert_url is not null");
            return (Criteria) this;
        }

        public Criteria andPi_cert_urlEqualTo(String value) {
            addCriterion("pi_cert_url =", value, "pi_cert_url");
            return (Criteria) this;
        }

        public Criteria andPi_cert_urlNotEqualTo(String value) {
            addCriterion("pi_cert_url <>", value, "pi_cert_url");
            return (Criteria) this;
        }

        public Criteria andPi_cert_urlGreaterThan(String value) {
            addCriterion("pi_cert_url >", value, "pi_cert_url");
            return (Criteria) this;
        }

        public Criteria andPi_cert_urlGreaterThanOrEqualTo(String value) {
            addCriterion("pi_cert_url >=", value, "pi_cert_url");
            return (Criteria) this;
        }

        public Criteria andPi_cert_urlLessThan(String value) {
            addCriterion("pi_cert_url <", value, "pi_cert_url");
            return (Criteria) this;
        }

        public Criteria andPi_cert_urlLessThanOrEqualTo(String value) {
            addCriterion("pi_cert_url <=", value, "pi_cert_url");
            return (Criteria) this;
        }

        public Criteria andPi_cert_urlLike(String value) {
            addCriterion("pi_cert_url like", value, "pi_cert_url");
            return (Criteria) this;
        }

        public Criteria andPi_cert_urlNotLike(String value) {
            addCriterion("pi_cert_url not like", value, "pi_cert_url");
            return (Criteria) this;
        }

        public Criteria andPi_cert_urlIn(List<String> values) {
            addCriterion("pi_cert_url in", values, "pi_cert_url");
            return (Criteria) this;
        }

        public Criteria andPi_cert_urlNotIn(List<String> values) {
            addCriterion("pi_cert_url not in", values, "pi_cert_url");
            return (Criteria) this;
        }

        public Criteria andPi_cert_urlBetween(String value1, String value2) {
            addCriterion("pi_cert_url between", value1, value2, "pi_cert_url");
            return (Criteria) this;
        }

        public Criteria andPi_cert_urlNotBetween(String value1, String value2) {
            addCriterion("pi_cert_url not between", value1, value2, "pi_cert_url");
            return (Criteria) this;
        }

        public Criteria andIssc_cert_urlIsNull() {
            addCriterion("issc_cert_url is null");
            return (Criteria) this;
        }

        public Criteria andIssc_cert_urlIsNotNull() {
            addCriterion("issc_cert_url is not null");
            return (Criteria) this;
        }

        public Criteria andIssc_cert_urlEqualTo(String value) {
            addCriterion("issc_cert_url =", value, "issc_cert_url");
            return (Criteria) this;
        }

        public Criteria andIssc_cert_urlNotEqualTo(String value) {
            addCriterion("issc_cert_url <>", value, "issc_cert_url");
            return (Criteria) this;
        }

        public Criteria andIssc_cert_urlGreaterThan(String value) {
            addCriterion("issc_cert_url >", value, "issc_cert_url");
            return (Criteria) this;
        }

        public Criteria andIssc_cert_urlGreaterThanOrEqualTo(String value) {
            addCriterion("issc_cert_url >=", value, "issc_cert_url");
            return (Criteria) this;
        }

        public Criteria andIssc_cert_urlLessThan(String value) {
            addCriterion("issc_cert_url <", value, "issc_cert_url");
            return (Criteria) this;
        }

        public Criteria andIssc_cert_urlLessThanOrEqualTo(String value) {
            addCriterion("issc_cert_url <=", value, "issc_cert_url");
            return (Criteria) this;
        }

        public Criteria andIssc_cert_urlLike(String value) {
            addCriterion("issc_cert_url like", value, "issc_cert_url");
            return (Criteria) this;
        }

        public Criteria andIssc_cert_urlNotLike(String value) {
            addCriterion("issc_cert_url not like", value, "issc_cert_url");
            return (Criteria) this;
        }

        public Criteria andIssc_cert_urlIn(List<String> values) {
            addCriterion("issc_cert_url in", values, "issc_cert_url");
            return (Criteria) this;
        }

        public Criteria andIssc_cert_urlNotIn(List<String> values) {
            addCriterion("issc_cert_url not in", values, "issc_cert_url");
            return (Criteria) this;
        }

        public Criteria andIssc_cert_urlBetween(String value1, String value2) {
            addCriterion("issc_cert_url between", value1, value2, "issc_cert_url");
            return (Criteria) this;
        }

        public Criteria andIssc_cert_urlNotBetween(String value1, String value2) {
            addCriterion("issc_cert_url not between", value1, value2, "issc_cert_url");
            return (Criteria) this;
        }

        public Criteria andClass_cert_urlIsNull() {
            addCriterion("class_cert_url is null");
            return (Criteria) this;
        }

        public Criteria andClass_cert_urlIsNotNull() {
            addCriterion("class_cert_url is not null");
            return (Criteria) this;
        }

        public Criteria andClass_cert_urlEqualTo(String value) {
            addCriterion("class_cert_url =", value, "class_cert_url");
            return (Criteria) this;
        }

        public Criteria andClass_cert_urlNotEqualTo(String value) {
            addCriterion("class_cert_url <>", value, "class_cert_url");
            return (Criteria) this;
        }

        public Criteria andClass_cert_urlGreaterThan(String value) {
            addCriterion("class_cert_url >", value, "class_cert_url");
            return (Criteria) this;
        }

        public Criteria andClass_cert_urlGreaterThanOrEqualTo(String value) {
            addCriterion("class_cert_url >=", value, "class_cert_url");
            return (Criteria) this;
        }

        public Criteria andClass_cert_urlLessThan(String value) {
            addCriterion("class_cert_url <", value, "class_cert_url");
            return (Criteria) this;
        }

        public Criteria andClass_cert_urlLessThanOrEqualTo(String value) {
            addCriterion("class_cert_url <=", value, "class_cert_url");
            return (Criteria) this;
        }

        public Criteria andClass_cert_urlLike(String value) {
            addCriterion("class_cert_url like", value, "class_cert_url");
            return (Criteria) this;
        }

        public Criteria andClass_cert_urlNotLike(String value) {
            addCriterion("class_cert_url not like", value, "class_cert_url");
            return (Criteria) this;
        }

        public Criteria andClass_cert_urlIn(List<String> values) {
            addCriterion("class_cert_url in", values, "class_cert_url");
            return (Criteria) this;
        }

        public Criteria andClass_cert_urlNotIn(List<String> values) {
            addCriterion("class_cert_url not in", values, "class_cert_url");
            return (Criteria) this;
        }

        public Criteria andClass_cert_urlBetween(String value1, String value2) {
            addCriterion("class_cert_url between", value1, value2, "class_cert_url");
            return (Criteria) this;
        }

        public Criteria andClass_cert_urlNotBetween(String value1, String value2) {
            addCriterion("class_cert_url not between", value1, value2, "class_cert_url");
            return (Criteria) this;
        }

        public Criteria andBoat_img_urlIsNull() {
            addCriterion("boat_img_url is null");
            return (Criteria) this;
        }

        public Criteria andBoat_img_urlIsNotNull() {
            addCriterion("boat_img_url is not null");
            return (Criteria) this;
        }

        public Criteria andBoat_img_urlEqualTo(String value) {
            addCriterion("boat_img_url =", value, "boat_img_url");
            return (Criteria) this;
        }

        public Criteria andBoat_img_urlNotEqualTo(String value) {
            addCriterion("boat_img_url <>", value, "boat_img_url");
            return (Criteria) this;
        }

        public Criteria andBoat_img_urlGreaterThan(String value) {
            addCriterion("boat_img_url >", value, "boat_img_url");
            return (Criteria) this;
        }

        public Criteria andBoat_img_urlGreaterThanOrEqualTo(String value) {
            addCriterion("boat_img_url >=", value, "boat_img_url");
            return (Criteria) this;
        }

        public Criteria andBoat_img_urlLessThan(String value) {
            addCriterion("boat_img_url <", value, "boat_img_url");
            return (Criteria) this;
        }

        public Criteria andBoat_img_urlLessThanOrEqualTo(String value) {
            addCriterion("boat_img_url <=", value, "boat_img_url");
            return (Criteria) this;
        }

        public Criteria andBoat_img_urlLike(String value) {
            addCriterion("boat_img_url like", value, "boat_img_url");
            return (Criteria) this;
        }

        public Criteria andBoat_img_urlNotLike(String value) {
            addCriterion("boat_img_url not like", value, "boat_img_url");
            return (Criteria) this;
        }

        public Criteria andBoat_img_urlIn(List<String> values) {
            addCriterion("boat_img_url in", values, "boat_img_url");
            return (Criteria) this;
        }

        public Criteria andBoat_img_urlNotIn(List<String> values) {
            addCriterion("boat_img_url not in", values, "boat_img_url");
            return (Criteria) this;
        }

        public Criteria andBoat_img_urlBetween(String value1, String value2) {
            addCriterion("boat_img_url between", value1, value2, "boat_img_url");
            return (Criteria) this;
        }

        public Criteria andBoat_img_urlNotBetween(String value1, String value2) {
            addCriterion("boat_img_url not between", value1, value2, "boat_img_url");
            return (Criteria) this;
        }

        public Criteria andCreate_idIsNull() {
            addCriterion("create_id is null");
            return (Criteria) this;
        }

        public Criteria andCreate_idIsNotNull() {
            addCriterion("create_id is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_idEqualTo(String value) {
            addCriterion("create_id =", value, "create_id");
            return (Criteria) this;
        }

        public Criteria andCreate_idNotEqualTo(String value) {
            addCriterion("create_id <>", value, "create_id");
            return (Criteria) this;
        }

        public Criteria andCreate_idGreaterThan(String value) {
            addCriterion("create_id >", value, "create_id");
            return (Criteria) this;
        }

        public Criteria andCreate_idGreaterThanOrEqualTo(String value) {
            addCriterion("create_id >=", value, "create_id");
            return (Criteria) this;
        }

        public Criteria andCreate_idLessThan(String value) {
            addCriterion("create_id <", value, "create_id");
            return (Criteria) this;
        }

        public Criteria andCreate_idLessThanOrEqualTo(String value) {
            addCriterion("create_id <=", value, "create_id");
            return (Criteria) this;
        }

        public Criteria andCreate_idLike(String value) {
            addCriterion("create_id like", value, "create_id");
            return (Criteria) this;
        }

        public Criteria andCreate_idNotLike(String value) {
            addCriterion("create_id not like", value, "create_id");
            return (Criteria) this;
        }

        public Criteria andCreate_idIn(List<String> values) {
            addCriterion("create_id in", values, "create_id");
            return (Criteria) this;
        }

        public Criteria andCreate_idNotIn(List<String> values) {
            addCriterion("create_id not in", values, "create_id");
            return (Criteria) this;
        }

        public Criteria andCreate_idBetween(String value1, String value2) {
            addCriterion("create_id between", value1, value2, "create_id");
            return (Criteria) this;
        }

        public Criteria andCreate_idNotBetween(String value1, String value2) {
            addCriterion("create_id not between", value1, value2, "create_id");
            return (Criteria) this;
        }

        public Criteria andCreate_dateIsNull() {
            addCriterion("create_date is null");
            return (Criteria) this;
        }

        public Criteria andCreate_dateIsNotNull() {
            addCriterion("create_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_dateEqualTo(Date value) {
            addCriterion("create_date =", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateNotEqualTo(Date value) {
            addCriterion("create_date <>", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateGreaterThan(Date value) {
            addCriterion("create_date >", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("create_date >=", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateLessThan(Date value) {
            addCriterion("create_date <", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateLessThanOrEqualTo(Date value) {
            addCriterion("create_date <=", value, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateIn(List<Date> values) {
            addCriterion("create_date in", values, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateNotIn(List<Date> values) {
            addCriterion("create_date not in", values, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateBetween(Date value1, Date value2) {
            addCriterion("create_date between", value1, value2, "create_date");
            return (Criteria) this;
        }

        public Criteria andCreate_dateNotBetween(Date value1, Date value2) {
            addCriterion("create_date not between", value1, value2, "create_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_idIsNull() {
            addCriterion("update_id is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_idIsNotNull() {
            addCriterion("update_id is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_idEqualTo(String value) {
            addCriterion("update_id =", value, "update_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_idNotEqualTo(String value) {
            addCriterion("update_id <>", value, "update_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_idGreaterThan(String value) {
            addCriterion("update_id >", value, "update_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_idGreaterThanOrEqualTo(String value) {
            addCriterion("update_id >=", value, "update_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_idLessThan(String value) {
            addCriterion("update_id <", value, "update_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_idLessThanOrEqualTo(String value) {
            addCriterion("update_id <=", value, "update_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_idLike(String value) {
            addCriterion("update_id like", value, "update_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_idNotLike(String value) {
            addCriterion("update_id not like", value, "update_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_idIn(List<String> values) {
            addCriterion("update_id in", values, "update_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_idNotIn(List<String> values) {
            addCriterion("update_id not in", values, "update_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_idBetween(String value1, String value2) {
            addCriterion("update_id between", value1, value2, "update_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_idNotBetween(String value1, String value2) {
            addCriterion("update_id not between", value1, value2, "update_id");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateIsNull() {
            addCriterion("update_date is null");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateIsNotNull() {
            addCriterion("update_date is not null");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateEqualTo(Date value) {
            addCriterion("update_date =", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateNotEqualTo(Date value) {
            addCriterion("update_date <>", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateGreaterThan(Date value) {
            addCriterion("update_date >", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateGreaterThanOrEqualTo(Date value) {
            addCriterion("update_date >=", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateLessThan(Date value) {
            addCriterion("update_date <", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateLessThanOrEqualTo(Date value) {
            addCriterion("update_date <=", value, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateIn(List<Date> values) {
            addCriterion("update_date in", values, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateNotIn(List<Date> values) {
            addCriterion("update_date not in", values, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateBetween(Date value1, Date value2) {
            addCriterion("update_date between", value1, value2, "update_date");
            return (Criteria) this;
        }

        public Criteria andUpdate_dateNotBetween(Date value1, Date value2) {
            addCriterion("update_date not between", value1, value2, "update_date");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_boat
     *
     * @mbg.generated do_not_delete_during_merge Wed Feb 17 15:25:17 CST 2021
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}