package com.zhang.example02mbg.entity;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class Customer implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.rowid
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private Integer rowid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.company_id
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String company_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.boat_code
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String boat_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.boat_name
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String boat_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.flag_country
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String flag_country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.contact
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.contact_phone
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String contact_phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.type
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.status
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.boat_length
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private BigDecimal boat_length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.boat_width
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private BigDecimal boat_width;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.boat_height
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private BigDecimal boat_height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.draft
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private BigDecimal draft;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.dead_weight
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private BigDecimal dead_weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.net_dead_weight
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private BigDecimal net_dead_weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.capacity
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private BigDecimal capacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.net_capacit
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private BigDecimal net_capacit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.bulk_capacity
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private BigDecimal bulk_capacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.bale_capacity
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private BigDecimal bale_capacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.hatch_size
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private BigDecimal hatch_size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.speed
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private BigDecimal speed;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.boat_class
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String boat_class;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.imo
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String imo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.crane
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String crane;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.mmsi
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String mmsi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.gps_no
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String gps_no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.build_date
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String build_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.boat_phone
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String boat_phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.boat_owner
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String boat_owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.pi_cert_url
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String pi_cert_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.issc_cert_url
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String issc_cert_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.class_cert_url
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String class_cert_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.boat_img_url
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String boat_img_url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.create_id
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String create_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.create_date
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private Date create_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.update_id
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private String update_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_boat.update_date
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private Date update_date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.rowid
     *
     * @return the value of t_boat.rowid
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public Integer getRowid() {
        return rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.rowid
     *
     * @param rowid the value for t_boat.rowid
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setRowid(Integer rowid) {
        this.rowid = rowid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.company_id
     *
     * @return the value of t_boat.company_id
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getCompany_id() {
        return company_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.company_id
     *
     * @param company_id the value for t_boat.company_id
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setCompany_id(String company_id) {
        this.company_id = company_id == null ? null : company_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.boat_code
     *
     * @return the value of t_boat.boat_code
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getBoat_code() {
        return boat_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.boat_code
     *
     * @param boat_code the value for t_boat.boat_code
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setBoat_code(String boat_code) {
        this.boat_code = boat_code == null ? null : boat_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.boat_name
     *
     * @return the value of t_boat.boat_name
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getBoat_name() {
        return boat_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.boat_name
     *
     * @param boat_name the value for t_boat.boat_name
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setBoat_name(String boat_name) {
        this.boat_name = boat_name == null ? null : boat_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.flag_country
     *
     * @return the value of t_boat.flag_country
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getFlag_country() {
        return flag_country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.flag_country
     *
     * @param flag_country the value for t_boat.flag_country
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setFlag_country(String flag_country) {
        this.flag_country = flag_country == null ? null : flag_country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.contact
     *
     * @return the value of t_boat.contact
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.contact
     *
     * @param contact the value for t_boat.contact
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setContact(String contact) {
        this.contact = contact == null ? null : contact.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.contact_phone
     *
     * @return the value of t_boat.contact_phone
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getContact_phone() {
        return contact_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.contact_phone
     *
     * @param contact_phone the value for t_boat.contact_phone
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setContact_phone(String contact_phone) {
        this.contact_phone = contact_phone == null ? null : contact_phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.type
     *
     * @return the value of t_boat.type
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.type
     *
     * @param type the value for t_boat.type
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.status
     *
     * @return the value of t_boat.status
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.status
     *
     * @param status the value for t_boat.status
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.boat_length
     *
     * @return the value of t_boat.boat_length
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public BigDecimal getBoat_length() {
        return boat_length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.boat_length
     *
     * @param boat_length the value for t_boat.boat_length
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setBoat_length(BigDecimal boat_length) {
        this.boat_length = boat_length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.boat_width
     *
     * @return the value of t_boat.boat_width
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public BigDecimal getBoat_width() {
        return boat_width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.boat_width
     *
     * @param boat_width the value for t_boat.boat_width
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setBoat_width(BigDecimal boat_width) {
        this.boat_width = boat_width;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.boat_height
     *
     * @return the value of t_boat.boat_height
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public BigDecimal getBoat_height() {
        return boat_height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.boat_height
     *
     * @param boat_height the value for t_boat.boat_height
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setBoat_height(BigDecimal boat_height) {
        this.boat_height = boat_height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.draft
     *
     * @return the value of t_boat.draft
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public BigDecimal getDraft() {
        return draft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.draft
     *
     * @param draft the value for t_boat.draft
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setDraft(BigDecimal draft) {
        this.draft = draft;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.dead_weight
     *
     * @return the value of t_boat.dead_weight
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public BigDecimal getDead_weight() {
        return dead_weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.dead_weight
     *
     * @param dead_weight the value for t_boat.dead_weight
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setDead_weight(BigDecimal dead_weight) {
        this.dead_weight = dead_weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.net_dead_weight
     *
     * @return the value of t_boat.net_dead_weight
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public BigDecimal getNet_dead_weight() {
        return net_dead_weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.net_dead_weight
     *
     * @param net_dead_weight the value for t_boat.net_dead_weight
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setNet_dead_weight(BigDecimal net_dead_weight) {
        this.net_dead_weight = net_dead_weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.capacity
     *
     * @return the value of t_boat.capacity
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public BigDecimal getCapacity() {
        return capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.capacity
     *
     * @param capacity the value for t_boat.capacity
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setCapacity(BigDecimal capacity) {
        this.capacity = capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.net_capacit
     *
     * @return the value of t_boat.net_capacit
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public BigDecimal getNet_capacit() {
        return net_capacit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.net_capacit
     *
     * @param net_capacit the value for t_boat.net_capacit
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setNet_capacit(BigDecimal net_capacit) {
        this.net_capacit = net_capacit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.bulk_capacity
     *
     * @return the value of t_boat.bulk_capacity
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public BigDecimal getBulk_capacity() {
        return bulk_capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.bulk_capacity
     *
     * @param bulk_capacity the value for t_boat.bulk_capacity
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setBulk_capacity(BigDecimal bulk_capacity) {
        this.bulk_capacity = bulk_capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.bale_capacity
     *
     * @return the value of t_boat.bale_capacity
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public BigDecimal getBale_capacity() {
        return bale_capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.bale_capacity
     *
     * @param bale_capacity the value for t_boat.bale_capacity
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setBale_capacity(BigDecimal bale_capacity) {
        this.bale_capacity = bale_capacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.hatch_size
     *
     * @return the value of t_boat.hatch_size
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public BigDecimal getHatch_size() {
        return hatch_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.hatch_size
     *
     * @param hatch_size the value for t_boat.hatch_size
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setHatch_size(BigDecimal hatch_size) {
        this.hatch_size = hatch_size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.speed
     *
     * @return the value of t_boat.speed
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public BigDecimal getSpeed() {
        return speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.speed
     *
     * @param speed the value for t_boat.speed
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setSpeed(BigDecimal speed) {
        this.speed = speed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.boat_class
     *
     * @return the value of t_boat.boat_class
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getBoat_class() {
        return boat_class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.boat_class
     *
     * @param boat_class the value for t_boat.boat_class
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setBoat_class(String boat_class) {
        this.boat_class = boat_class == null ? null : boat_class.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.imo
     *
     * @return the value of t_boat.imo
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getImo() {
        return imo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.imo
     *
     * @param imo the value for t_boat.imo
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setImo(String imo) {
        this.imo = imo == null ? null : imo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.crane
     *
     * @return the value of t_boat.crane
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getCrane() {
        return crane;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.crane
     *
     * @param crane the value for t_boat.crane
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setCrane(String crane) {
        this.crane = crane == null ? null : crane.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.mmsi
     *
     * @return the value of t_boat.mmsi
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getMmsi() {
        return mmsi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.mmsi
     *
     * @param mmsi the value for t_boat.mmsi
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setMmsi(String mmsi) {
        this.mmsi = mmsi == null ? null : mmsi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.gps_no
     *
     * @return the value of t_boat.gps_no
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getGps_no() {
        return gps_no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.gps_no
     *
     * @param gps_no the value for t_boat.gps_no
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setGps_no(String gps_no) {
        this.gps_no = gps_no == null ? null : gps_no.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.build_date
     *
     * @return the value of t_boat.build_date
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getBuild_date() {
        return build_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.build_date
     *
     * @param build_date the value for t_boat.build_date
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setBuild_date(String build_date) {
        this.build_date = build_date == null ? null : build_date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.boat_phone
     *
     * @return the value of t_boat.boat_phone
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getBoat_phone() {
        return boat_phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.boat_phone
     *
     * @param boat_phone the value for t_boat.boat_phone
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setBoat_phone(String boat_phone) {
        this.boat_phone = boat_phone == null ? null : boat_phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.boat_owner
     *
     * @return the value of t_boat.boat_owner
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getBoat_owner() {
        return boat_owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.boat_owner
     *
     * @param boat_owner the value for t_boat.boat_owner
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setBoat_owner(String boat_owner) {
        this.boat_owner = boat_owner == null ? null : boat_owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.pi_cert_url
     *
     * @return the value of t_boat.pi_cert_url
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getPi_cert_url() {
        return pi_cert_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.pi_cert_url
     *
     * @param pi_cert_url the value for t_boat.pi_cert_url
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setPi_cert_url(String pi_cert_url) {
        this.pi_cert_url = pi_cert_url == null ? null : pi_cert_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.issc_cert_url
     *
     * @return the value of t_boat.issc_cert_url
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getIssc_cert_url() {
        return issc_cert_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.issc_cert_url
     *
     * @param issc_cert_url the value for t_boat.issc_cert_url
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setIssc_cert_url(String issc_cert_url) {
        this.issc_cert_url = issc_cert_url == null ? null : issc_cert_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.class_cert_url
     *
     * @return the value of t_boat.class_cert_url
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getClass_cert_url() {
        return class_cert_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.class_cert_url
     *
     * @param class_cert_url the value for t_boat.class_cert_url
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setClass_cert_url(String class_cert_url) {
        this.class_cert_url = class_cert_url == null ? null : class_cert_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.boat_img_url
     *
     * @return the value of t_boat.boat_img_url
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getBoat_img_url() {
        return boat_img_url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.boat_img_url
     *
     * @param boat_img_url the value for t_boat.boat_img_url
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setBoat_img_url(String boat_img_url) {
        this.boat_img_url = boat_img_url == null ? null : boat_img_url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.create_id
     *
     * @return the value of t_boat.create_id
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getCreate_id() {
        return create_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.create_id
     *
     * @param create_id the value for t_boat.create_id
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setCreate_id(String create_id) {
        this.create_id = create_id == null ? null : create_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.create_date
     *
     * @return the value of t_boat.create_date
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public Date getCreate_date() {
        return create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.create_date
     *
     * @param create_date the value for t_boat.create_date
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setCreate_date(Date create_date) {
        this.create_date = create_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.update_id
     *
     * @return the value of t_boat.update_id
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public String getUpdate_id() {
        return update_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.update_id
     *
     * @param update_id the value for t_boat.update_id
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setUpdate_id(String update_id) {
        this.update_id = update_id == null ? null : update_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_boat.update_date
     *
     * @return the value of t_boat.update_date
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public Date getUpdate_date() {
        return update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_boat.update_date
     *
     * @param update_date the value for t_boat.update_date
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    public void setUpdate_date(Date update_date) {
        this.update_date = update_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rowid=").append(rowid);
        sb.append(", company_id=").append(company_id);
        sb.append(", boat_code=").append(boat_code);
        sb.append(", boat_name=").append(boat_name);
        sb.append(", flag_country=").append(flag_country);
        sb.append(", contact=").append(contact);
        sb.append(", contact_phone=").append(contact_phone);
        sb.append(", type=").append(type);
        sb.append(", status=").append(status);
        sb.append(", boat_length=").append(boat_length);
        sb.append(", boat_width=").append(boat_width);
        sb.append(", boat_height=").append(boat_height);
        sb.append(", draft=").append(draft);
        sb.append(", dead_weight=").append(dead_weight);
        sb.append(", net_dead_weight=").append(net_dead_weight);
        sb.append(", capacity=").append(capacity);
        sb.append(", net_capacit=").append(net_capacit);
        sb.append(", bulk_capacity=").append(bulk_capacity);
        sb.append(", bale_capacity=").append(bale_capacity);
        sb.append(", hatch_size=").append(hatch_size);
        sb.append(", speed=").append(speed);
        sb.append(", boat_class=").append(boat_class);
        sb.append(", imo=").append(imo);
        sb.append(", crane=").append(crane);
        sb.append(", mmsi=").append(mmsi);
        sb.append(", gps_no=").append(gps_no);
        sb.append(", build_date=").append(build_date);
        sb.append(", boat_phone=").append(boat_phone);
        sb.append(", boat_owner=").append(boat_owner);
        sb.append(", pi_cert_url=").append(pi_cert_url);
        sb.append(", issc_cert_url=").append(issc_cert_url);
        sb.append(", class_cert_url=").append(class_cert_url);
        sb.append(", boat_img_url=").append(boat_img_url);
        sb.append(", create_id=").append(create_id);
        sb.append(", create_date=").append(create_date);
        sb.append(", update_id=").append(update_id);
        sb.append(", update_date=").append(update_date);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}