package com.zhang.example02mbg.dao;

import com.zhang.example02mbg.entity.Customer;
import com.zhang.example02mbg.entity.CustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    long countByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    int deleteByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    int deleteByPrimaryKey(Integer rowid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    List<Customer> selectByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    Customer selectByPrimaryKey(Integer rowid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_boat
     *
     * @mbg.generated Wed Feb 17 15:25:17 CST 2021
     */
    int updateByPrimaryKey(Customer record);
}